### ISSUE TITLE
Don't have d. when there is text in death date

### ISSUE THREAD

**Issue by pooya-raz** [pooya-raz/tub-text-service#5]
Some entries have "fl." or "alive in" in the text for the Author's date of death. Output is currently appending "d." to all dates. Needs to check if there is a text before the year, and if so, do not apply the "d."

**Comment by KumailRajani** [comment]
The formula that "d." should not appear when there is text in the dates would not apply when the text is "after 1129/after 1716". Here we want "d. after 1129/after 1716". Please do necessary. Thanks

**Comment by KumailRajani** [comment]
and also here:



![Image](https://user-images.githubusercontent.com/109080361/190583899-b0f67f8e-7bca-4347-9172-b3040af02865.png)

we want "d. before" here
